library(tcltk)
library(dgread)
.Tcl("package require dlsh; package require dlsh")
.Tcl("package require loaddata")
.Tcl("cd l:/projects/analysis/sheinb")
.Tcl("source dynamic.tcl")
.Tcl("set g [dynamic::load m_center*_011106*]")
.Tcl("set out [dg_create]")
.Tcl("dl_set $out:delay $g:delay")
.Tcl("dl_set $out:target_contrast $g:target_contrast")
.Tcl("dl_set $out:delay_invalid $g:delay_invalid")
.Tcl("dl_set $out:rts $g:rts")
.Tcl("dl_set $out:status $g:status")
.Tcl("dg_write group2 __transfer")
g <- data.frame(read.dgz("__transfer"))
unlink("__transfer")
summary(g)
